const game = [
    {
        level: '1',
        items: [
            require('../assets/game/1.png'),
            require('../assets/game/4.png'),
            require('../assets/game/5.png'),
            require('../assets/game/6.png'),
            require('../assets/game/7.png'),
            require('../assets/game/8.png'),
            require('../assets/game/9.png'),
            require('../assets/game/10.png'),
            require('../assets/game/12.png'),
        ],
        correct: [
            require('../assets/game/1.png'),
            require('../assets/game/7.png'),
            require('../assets/game/8.png'),
            require('../assets/game/12.png'),
        ],
        points: 0,
        text: '🎉 Time well traveled! You`ve mastered history!'
    },
    {
        level: '2',
        items: [
            require('../assets/game/1.png'),
            require('../assets/game/2.png'),
            require('../assets/game/3.png'),
            require('../assets/game/4.png'),
            require('../assets/game/5.png'),
            require('../assets/game/6.png'),
            require('../assets/game/9.png'),
            require('../assets/game/10.png'),
            require('../assets/game/12.png'),
        ],
        correct: [
            require('../assets/game/2.png'),
            require('../assets/game/4.png'),
            require('../assets/game/5.png'),
            require('../assets/game/6.png'),
            require('../assets/game/10.png'),
            require('../assets/game/12.png'),
        ],
        points: 40,
        text: '🏆 Victory through the ages! You nailed it!'
    },
    {
        level: '3',
        items: [
            require('../assets/game/1.png'),
            require('../assets/game/2.png'),
            require('../assets/game/3.png'),
            require('../assets/game/4.png'),
            require('../assets/game/5.png'),
            require('../assets/game/7.png'),
            require('../assets/game/9.png'),
            require('../assets/game/11.png'),
            require('../assets/game/12.png'),
        ],
        correct: [
            require('../assets/game/1.png'),
            require('../assets/game/2.png'),
            require('../assets/game/3.png'),
            require('../assets/game/5.png'),
            require('../assets/game/7.png'),
            require('../assets/game/9.png'),
            require('../assets/game/11.png'),
            require('../assets/game/12.png'),
        ],
        points: 60,
        text: '⏳ You’ve cracked the timeline! Well done!'
    },
    {
        level: '4',
        items: [
            require('../assets/game/1.png'),
            require('../assets/game/2.png'),
            require('../assets/game/3.png'),
            require('../assets/game/4.png'),
            require('../assets/game/5.png'),
            require('../assets/game/6.png'),
            require('../assets/game/7.png'),
            require('../assets/game/8.png'),
            require('../assets/game/9.png'),
            require('../assets/game/10.png'),
            require('../assets/game/11.png'),
            require('../assets/game/12.png'),
        ],
        correct: [
            require('../assets/game/3.png'),
            require('../assets/game/4.png'),
            require('../assets/game/5.png'),
            require('../assets/game/6.png'),
            require('../assets/game/7.png'),
            require('../assets/game/8.png'),
            require('../assets/game/9.png'),
            require('../assets/game/11.png'),
            require('../assets/game/12.png'),
        ],
        points: 80,
        text: '🚀 A true time explorer! You know your artifacts!'
    },
    {
        level: '5',
        items: [
            require('../assets/game/1.png'),
            require('../assets/game/2.png'),
            require('../assets/game/3.png'),
            require('../assets/game/4.png'),
            require('../assets/game/5.png'),
            require('../assets/game/6.png'),
            require('../assets/game/7.png'),
            require('../assets/game/8.png'),
            require('../assets/game/9.png'),
            require('../assets/game/10.png'),
            require('../assets/game/11.png'),
            require('../assets/game/12.png'),
        ],
        correct: [
            require('../assets/game/1.png'),
            require('../assets/game/2.png'),
            require('../assets/game/3.png'),
            require('../assets/game/4.png'),
            require('../assets/game/5.png'),
            require('../assets/game/6.png'),
            require('../assets/game/7.png'),
            require('../assets/game/8.png'),
            require('../assets/game/9.png'),
            require('../assets/game/10.png'),
            require('../assets/game/12.png'),
        ],
        points: 90,
        text: '🔥 History bows to your knowledge! Epic win!'
    }
];

export default game;